# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(653, 446)
        Dialog.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_show_title = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb_show_title.setFont(font)
        self.lb_show_title.setStyleSheet("")
        self.lb_show_title.setText("")
        self.lb_show_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_show_title.setProperty("title", "")
        self.lb_show_title.setObjectName("lb_show_title")
        self.verticalLayout.addWidget(self.lb_show_title)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setStyleSheet("background:blue")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.lb_show_msg = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.lb_show_msg.setFont(font)
        self.lb_show_msg.setStyleSheet("")
        self.lb_show_msg.setText("")
        self.lb_show_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_show_msg.setObjectName("lb_show_msg")
        self.verticalLayout.addWidget(self.lb_show_msg)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_check = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btn_check.setFont(font)
        self.btn_check.setStyleSheet("height:80px;\n"
"background:#66ccff;\n"
"")
        self.btn_check.setObjectName("btn_check")
        self.horizontalLayout.addWidget(self.btn_check)
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("height:80px;\n"
"background:#66ccff;\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_check.setText(_translate("Dialog", "Again"))
        self.btn_cancel.setText(_translate("Dialog", "close"))
