PROJECT_FOLDER = ''
TRAIN_FOLDER = ''
VAL_FOLDER = ''

# train 指令參數
PERCENT = 90
TRAIN_WEIGHTS = ''
DATA = ''
IMG_SIZE = ['224x224', '320x320', '416x416', '640x640']
DEVICE = ['CPU', 'GPU 1顆', 'GPU 2顆', 'GPU 3顆']


# 訓練模型 訓練尺寸 批次數量 訓練次數 硬體設備
TRAIN_IMG_SIZE = [320, 320]
TRAIN_BATCH_SIZE = 2
TRAIN_EPOCHS = 1
TRAIN_DEVICE = 'cpu'

# predict 指令參數
PREDICT_WEIGHTS = ''
PREDICT_SOURCE = ''
PREDICT_DEVICE = 'cpu'

RESULT = ''
